services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: kazaUser
      POSTGRES_PASSWORD: kaza123&!
      POSTGRES_DB: testExpressDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  express-api:
    build: .  
    container_name: express-api
    restart: always
    depends_on:
      - postgres
    environment:
      db_url: postgres://kazaUser:kaza123%26%21@postgres:5432/testExpressDb
    ports:
      - "3001:3001"

volumes:
  postgres_data:
